/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Service health probe. Per-provider shape locked in D-10.
         *
         *     Returns::
         *
         *         {
         *           "status": "ok" | "degraded",
         *           "version": "<str>",
         *           "providers": {
         *             "local": {
         *               "kind": "ollama",
         *               "state": "ready" | "warming" | "unhealthy",
         *               "last_error": null | "<exc_class_name>"
         *             }
         *           }
         *         }
         *
         *     Aggregate ``status`` is ``"ok"`` iff every provider reports
         *     ``state == "ready"``. Phase 2 has a single local provider; Phase 4
         *     adds lmstudio in the "local" slot; Phase 5 adds "frontier" as a
         *     separate sibling provider block.
         *
         *     Body intentionally omits dependency versions / internals (T-01-31).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description D-13: route body is the orchestrator call.
         *
         *     - Pydantic validates the request body.
         *     - `stream=True` returns OpenAI-compatible server-sent events after the
         *       orchestrator has decided whether to keep local or pivot to frontier.
         *     - CoreThreadError subclasses bubble to `_corethread_error_handler`
         *       (OpenAI-shape error envelope).
         *     - Uncaught exceptions bubble to `_generic_error_handler` (500 envelope).
         */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description D-08 + D-09 + D-10: return configured local + frontier models.
         *
         *     Judge model is EXCLUDED (internal control-loop detail, not routable).
         *     If local.model == frontier.model, dedupe to a single entry (D-08).
         *     `created` is the service-lifetime startup timestamp (D-09).
         *     `owned_by` is the `ModelEntry` class-locked Literal "corethread".
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the redacted ConfigView. D-09: Cache-Control: no-cache.
         *
         *     Config is restart-only mutable in v1.1; an operator hot-edits config.yaml
         *     and restarts → the browser MUST re-fetch. Hand-rolled JSONResponse so we
         *     can attach the no-cache header alongside the validated body.
         */
        get: operations["get_config_v1_config_get"];
        /**
         * Put Config
         * @description Persist config.yaml without writing resolved API keys.
         */
        put: operations["put_config_v1_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Corethread
         * @description Local-only admin endpoint used by the config UI after restart-required saves.
         */
        post: operations["restart_corethread_v1_admin_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Config Profile
         * @description Probe a single model profile and return sanitized model-list results.
         */
        post: operations["probe_config_profile_v1_config_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/route/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Activity Stream
         * @description SSE stream of body-free route activity events for the live UI graphic.
         */
        get: operations["route_activity_stream_v1_route_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/_route_activity_event_schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI schema for SSE route activity events. Returns 410 - events are streamed via /v1/route/stream. */
        get: operations["_route_activity_event_schema_v1__route_activity_event_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Traces Stream
         * @description SSE stream of RequestTrace events. Native fastapi.sse, ping=15 (D-13).
         *
         *     D-10 drain-then-stream: if Last-Event-ID is present, drain the replay-
         *     seeded queue UNTIL we see a trace with matching request_id, then enter
         *     live mode (the next q.get() yields the first NEW event after disconnect).
         *     D-11: if no match is found (unknown ID), the drain loop completes and
         *     we fall through to live mode — frontend dedupes by request_id (Phase 10).
         *
         *     Pitfall 20: request.is_disconnected() polled once per asyncio.wait_for
         *     timeout (1.0s). Phase 7 D-04's asynccontextmanager try/finally
         *     guarantees bus.subscribe()'s queue is unregistered on every exit path.
         *
         *     Pitfall 18: TraceEvent.model_validate(t).model_dump_json() is the
         *     runtime drift catch — extra='forbid' rejects any future RequestTrace
         *     field that a hypothetical (forbidden) obs.py mutation might add.
         */
        get: operations["traces_stream_v1_traces_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{request_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Transcript */
        get: operations["get_trace_transcript_v1_traces__request_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trace Transcripts */
        get: operations["list_trace_transcripts_v1_transcripts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/_traces_event_schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI schema for SSE trace events. Returns 410 — events are streamed via /v1/traces/stream. */
        get: operations["_traces_event_schema_v1__traces_event_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return a window-scoped StatsAggregator snapshot.
         *
         *     D-16: `window: Window = "all"` — FastAPI auto-validates the query string
         *     against the Literal["1h","24h","7d","all"] (imported from
         *     corethread.stats). Invalid values raise RequestValidationError, which
         *     routes through main.py:359's existing handler → OpenAI-shape 400
         *     envelope. Zero new error-path code.
         *
         *     D-09: Cache-Control: no-cache so a hot snapshot reflects the
         *     latest aggregator state on every UI re-fetch.
         */
        get: operations["get_stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminRestartResponse
         * @description Response from the local-only admin restart endpoint.
         */
        AdminRestartResponse: {
            /**
             * Status
             * @constant
             */
            status: "restarting";
            /** Message */
            message: string;
        };
        /**
         * ChatCompletionRequest
         * @description OpenAI chat-completion request body.
         *
         *     `extra="allow"` per CONTEXT.md — forward-compat: an SDK client sending
         *     a future field like `reasoning_effort` validates without error and the
         *     field survives `.model_dump()` for forwarding to the chosen provider.
         *
         *     `tools` / `tool_choice` are defined as optional permissive (CONTEXT.md
         *     decision): v1 accepts and forwards them but does NOT execute them.
         */
        ChatCompletionRequest: {
            /** Model */
            model: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** N */
            n?: number | null;
            /** Stop */
            stop?: string | string[] | null;
            /** Stream */
            stream?: boolean | null;
            /** Response Format */
            response_format?: {
                [key: string]: unknown;
            } | null;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /** Tool Choice */
            tool_choice?: string | {
                [key: string]: unknown;
            } | null;
            /** Seed */
            seed?: number | null;
            /** User */
            user?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionResponse
         * @description OpenAI chat-completion response body.
         *
         *     `extra="allow"` so provider-specific extras (Ollama's `system_fingerprint`,
         *     `eval_count`, `total_duration`, etc.) can survive a round-trip when a
         *     future adapter chooses to preserve them. The CANONICAL construction path
         *     is `to_openai_chat_completion(...)` — adapters MUST go through that
         *     helper (T-01-11 mitigation) so the required surface is always populated.
         *
         *     `usage` is REQUIRED (not Optional) — Pitfall #1 calls out missing `usage`
         *     as the most common shape-drift bug; the adapter always synthesizes it.
         */
        ChatCompletionResponse: {
            /** Id */
            id: string;
            /**
             * Object
             * @default chat.completion
             * @constant
             */
            object: "chat.completion";
            /** Created */
            created: number;
            /** Model */
            model: string;
            /** Choices */
            choices: components["schemas"]["Choice"][];
            usage: components["schemas"]["Usage"];
            /** System Fingerprint */
            system_fingerprint?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatMessage
         * @description OpenAI chat message. Accepts text content or list-of-content-parts (multimodal).
         *
         *     `extra="allow"` per CONTEXT.md — keeps unknown OpenAI message fields
         *     (e.g. tool-related additions in future API revisions) passing through
         *     untouched. v1 does not interpret multimodal parts; `content` typed as
         *     `str | list[dict]` accepts both shapes without parsing.
         */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content?: string | {
                [key: string]: unknown;
            }[] | null;
            /** Name */
            name?: string | null;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[] | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Choice
         * @description One element of `ChatCompletionResponse.choices`.
         *
         *     `finish_reason` is typed as the closed `FinishReason` Literal — `None`
         *     is structurally INVALID. This forces every code path that constructs a
         *     `Choice` to map an upstream `None` via `OLLAMA_FINISH_MAP` (Pitfall #2).
         */
        Choice: {
            /** Index */
            index: number;
            message: components["schemas"]["ChatMessage"];
            /**
             * Finish Reason
             * @enum {string}
             */
            finish_reason: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
        } & {
            [key: string]: unknown;
        };
        /**
         * ConfigProbeResult
         * @description Sanitized provider probe result for the config editor.
         */
        ConfigProbeResult: {
            /** Ok */
            ok: boolean;
            /**
             * Provider
             * @enum {string}
             */
            provider: "ollama" | "lmstudio" | "openai" | "openrouter";
            /** Models */
            models?: string[];
            /** Selected Model Available */
            selected_model_available?: boolean | null;
            /** Error Class */
            error_class?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ConfigView
         * @description Top-level /v1/config response — extra='forbid' (D-22 lock).
         *
         *     Mirrors AppConfig.{local, judge, frontier, routing} via the hand-rolled
         *     to_config_view(cfg) builder (D-08 allowlist semantics — a future
         *     AppConfig field defaults to NOT EXPOSED unless someone explicitly adds
         *     it to a sub-view here).
         */
        ConfigView: {
            local: components["schemas"]["LocalView"];
            judge: components["schemas"]["JudgeView"];
            frontier: components["schemas"]["FrontierView"];
            routing: components["schemas"]["RoutingView"];
            /** Model Profiles */
            model_profiles: {
                [key: string]: components["schemas"]["ModelProfileView"];
            };
            role_profiles: components["schemas"]["RoleProfilesView"];
            ui: components["schemas"]["UiView"];
            privacy: components["schemas"]["PrivacyView"];
            controls: components["schemas"]["ControlsView"];
        };
        /**
         * ControlsView
         * @description Rate limits, quotas, billing estimates, and body-free audit logging.
         */
        ControlsView: {
            /** Requests Per Minute */
            requests_per_minute?: number | null;
            /** Daily Request Quota */
            daily_request_quota?: number | null;
            /** Daily Token Quota */
            daily_token_quota?: number | null;
            /** Daily Cost Quota Usd */
            daily_cost_quota_usd?: number | null;
            /** Pricing */
            pricing?: {
                [key: string]: components["schemas"]["ModelPricingView"];
            };
            /**
             * Audit Enabled
             * @default false
             */
            audit_enabled: boolean;
            /**
             * Audit Path
             * @default outputs/audit.jsonl
             */
            audit_path: string;
            /**
             * Audit Include Request Body
             * @default false
             */
            audit_include_request_body: boolean;
        };
        /**
         * FrontierView
         * @description Frontier block exposed in /v1/config — D-07 / Pitfall 19 LOCKED.
         *
         *     Fields are EXACTLY (model, api_key_env, max_tokens). NEVER add api_key.
         *     NEVER add api_key_resolved. NEVER add base_url (D-07 omits internal-only
         *     endpoint URL). Pitfall 19 + CFG-02 + SEC-03 anchor here.
         */
        FrontierView: {
            /** Model */
            model: string;
            /** Api Key Env */
            api_key_env: string;
            /** Max Tokens */
            max_tokens: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgeView
         * @description Mirror of JudgeConfigModel. Contains no secrets.
         */
        JudgeView: {
            /** Model */
            model: string;
            /** Prompt */
            prompt: string;
        };
        /**
         * LocalView
         * @description Mirror of LocalConfig (corethread/models.py) — no secrets, plain copy.
         */
        LocalView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ollama" | "lmstudio";
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /** Num Ctx Default */
            num_ctx_default: number;
            /** Num Ctx Overrides */
            num_ctx_overrides: {
                [key: string]: number;
            };
        };
        /**
         * ModelEntry
         * @description One element of GET /v1/models `data` list.
         *
         *     D-10: internal contract — `extra='forbid'`. `owned_by` is type-locked to
         *     the Literal "corethread" (Claude's Discretion) so no call site can smuggle
         *     a different ownership string at construction. `created` is an int unix
         *     timestamp captured once at service startup (set in main.py lifespan as
         *     `app.state.models_created_at`) — same value across every entry in one
         *     service lifetime, per D-09.
         */
        ModelEntry: {
            /** Id */
            id: string;
            /**
             * Object
             * @default model
             * @constant
             */
            object: "model";
            /** Created */
            created: number;
            /**
             * Owned By
             * @default corethread
             * @constant
             */
            owned_by: "corethread";
        };
        /**
         * ModelPricingView
         * @description Public config view of per-model billing rates.
         */
        ModelPricingView: {
            /**
             * Input Per 1M Tokens
             * @default 0
             */
            input_per_1m_tokens: number;
            /**
             * Output Per 1M Tokens
             * @default 0
             */
            output_per_1m_tokens: number;
        };
        /**
         * ModelProfileView
         * @description Reusable model/provider profile surfaced for the config editor.
         */
        ModelProfileView: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "ollama" | "lmstudio" | "openai" | "openrouter";
            /** Model */
            model: string;
            /** Base Url */
            base_url: string;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Timeout S */
            timeout_s?: number | null;
            /** Num Ctx Default */
            num_ctx_default?: number | null;
            /** Num Ctx Overrides */
            num_ctx_overrides?: {
                [key: string]: number;
            };
        };
        /**
         * ModelsListResponse
         * @description GET /v1/models envelope (D-09 + D-10).
         */
        ModelsListResponse: {
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
            /** Data */
            data: components["schemas"]["ModelEntry"][];
        };
        /**
         * PrivacyView
         * @description Privacy-sensitive local debugging settings.
         */
        PrivacyView: {
            /**
             * Capture Transcripts
             * @default false
             */
            capture_transcripts: boolean;
            /**
             * Transcript Max
             * @default 25
             */
            transcript_max: number;
        };
        /**
         * RoleProfilesView
         * @description Active model profile ids for CoreThread roles.
         */
        RoleProfilesView: {
            /** Local */
            local: string;
            /** Judge */
            judge: string;
            /** Frontier */
            frontier: string;
        };
        /**
         * RouteActivityEventView
         * @description Body-free SSE payload for the live route graphic.
         */
        RouteActivityEventView: {
            /** Request Id */
            request_id: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "received" | "local_started" | "local_completed" | "local_error" | "judge_started" | "judge_completed" | "judge_error" | "frontier_started" | "frontier_completed" | "frontier_error" | "completed" | "error";
            /** Selected Local Model */
            selected_local_model: string | null;
            /** Judge Model */
            judge_model: string | null;
            /** Frontier Model */
            frontier_model: string | null;
            /** Pivoted */
            pivoted: boolean | null;
            /** Confidence Score */
            confidence_score: number | null;
            /** Error Class */
            error_class: string | null;
            /** Ts Ms */
            ts_ms: number;
        };
        /**
         * RoutingView
         * @description Mirror of RoutingConfig — threshold + constraint_prompt (CFG-03 cost lever).
         */
        RoutingView: {
            /** Threshold */
            threshold: number;
            /** Constraint Prompt */
            constraint_prompt: string;
        };
        /**
         * StatsSnapshotEmpty
         * @description Empty-window snapshot — 4 keys (D-15 / Phase 8 D-09 #1).
         *
         *     Returned when window_size == 0 (no traces in the requested window).
         *     Discriminator: `window_size: Literal[0]` for clean Phase 10 type-gen
         *     narrowing.
         */
        StatsSnapshotEmpty: {
            /** Window Started At */
            window_started_at: number;
            /**
             * Window Size
             * @constant
             */
            window_size: 0;
            /** Max Window Size */
            max_window_size: number;
            /** Note */
            note: string;
        };
        /**
         * StatsSnapshotPopulated
         * @description Populated-window snapshot — 12 keys (D-15 / Phase 8 D-09 #2).
         *
         *     pivot_reasons is always-4-buckets per Phase 8 D-07 (_PIVOT_REASON_BUCKETS
         *     constant). Each quantile dict can be None on empty-after-filter (e.g.,
         *     no pivots in window → frontier_latency_ms is None; all traces have
         *     judge_parse_failed=True → confidence_score is None).
         */
        StatsSnapshotPopulated: {
            /** Window Started At */
            window_started_at: number;
            /** Window Size */
            window_size: number;
            /** Max Window Size */
            max_window_size: number;
            /** Pivot Rate */
            pivot_rate: number;
            /** Pivot Reasons */
            pivot_reasons: {
                [key: string]: number;
            };
            /** Tokens In Total */
            tokens_in_total: number;
            /** Tokens Out Total */
            tokens_out_total: number;
            local_latency_ms: components["schemas"]["_Quantiles"] | null;
            judge_latency_ms: components["schemas"]["_Quantiles"] | null;
            frontier_latency_ms: components["schemas"]["_Quantiles"] | null;
            confidence_score: components["schemas"]["_Quantiles"] | null;
            /** Note */
            note: string;
        };
        /**
         * TraceEvent
         * @description SSE event payload for /v1/traces/stream — TRC-09 schema lock.
         *
         *     15 fields verbatim from corethread.obs.RequestTrace. extra='forbid' is
         *     the structural Pitfall 18 defense. The model is also the OpenAPI
         *     publication target via /v1/_traces_event_schema (D-14).
         */
        TraceEvent: {
            /** Request Id */
            request_id: string;
            /** Selected Local Model */
            selected_local_model: string;
            /** Judge Model */
            judge_model: string;
            /** Frontier Model */
            frontier_model: string | null;
            /** Confidence Score */
            confidence_score: number;
            /** Pivoted */
            pivoted: boolean;
            /** Local Latency Ms */
            local_latency_ms: number;
            /** Judge Latency Ms */
            judge_latency_ms: number;
            /** Frontier Latency Ms */
            frontier_latency_ms: number | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Frontier Cost Est */
            frontier_cost_est: number | null;
            /** Judge Parse Failed */
            judge_parse_failed: boolean;
            /**
             * Pivot Reason
             * @enum {string}
             */
            pivot_reason:
                | "none"
                | "low_score"
                | "local_truncated"
                | "local_error"
                | "judge_error";
            /** Local Error Class */
            local_error_class: string | null;
        };
        /** TraceTranscriptListView */
        TraceTranscriptListView: {
            /** Maxlen */
            maxlen: number;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["TraceTranscriptView"][];
        };
        /**
         * TraceTranscriptView
         * @description Prompt/response transcript for a retained trace.
         *
         *     Unlike TraceEvent, this model intentionally carries request/response text.
         *     It is returned only from explicit transcript endpoints, never from SSE or
         *     stats.
         */
        TraceTranscriptView: {
            /** Request Id */
            request_id: string;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /** Request Messages */
            request_messages: {
                [key: string]: unknown;
            }[];
            /** Local Response */
            local_response: string | null;
            /** Judge Response */
            judge_response: string | null;
            /** Frontier Response */
            frontier_response: string | null;
            /** Final Response */
            final_response: string | null;
            /**
             * Final Response Source
             * @enum {string}
             */
            final_response_source: "local" | "frontier" | "none";
            trace: components["schemas"]["TraceEvent"] | null;
            /** Errors */
            errors: {
                [key: string]: string;
            };
        };
        /**
         * UiView
         * @description Persisted UI preferences.
         */
        UiView: {
            /**
             * Theme
             * @default system
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
        };
        /**
         * Usage
         * @description OpenAI token-count surface.
         *
         *     All three counts are REQUIRED so typed-SDK clients (which expect
         *     `usage.prompt_tokens` etc. to be non-null) never break. The adapter
         *     `to_openai_chat_completion(...)` always synthesizes a `Usage`, even if
         *     the upstream provider omitted the count (zeros are valid).
         */
        Usage: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * _Quantiles
         * @description Mirrors stats._quantiles() return dict — 4-field quantile descriptor.
         */
        _Quantiles: {
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** Max */
            max: number;
            /** Min */
            min: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsListResponse"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    put_config_v1_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigView"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_corethread_v1_admin_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRestartResponse"];
                };
            };
        };
    };
    probe_config_profile_v1_config_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfileView"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigProbeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_activity_stream_v1_route_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    _route_activity_event_schema_v1__route_activity_event_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteActivityEventView"];
                };
            };
        };
    };
    traces_stream_v1_traces_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    get_trace_transcript_v1_traces__request_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceTranscriptView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trace_transcripts_v1_transcripts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceTranscriptListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _traces_event_schema_v1__traces_event_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceEvent"];
                };
            };
        };
    };
    get_stats_v1_stats_get: {
        parameters: {
            query?: {
                window?: "1h" | "24h" | "7d" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSnapshotEmpty"] | components["schemas"]["StatsSnapshotPopulated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
